name: flutter_camera_app
description: A flutter application that demonstrate how to add camera to flutter and share captured image file.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.5.2+1
  # path_provider: ^0.5.0+1
  path_provider: ^1.1.2
  path: ^1.6.2
  esys_flutter_share: ^1.0.1
  http: ^0.12.0+2
  dio: ^3.0.9
  image_picker: ^0.6.5+3
  loading: ^1.0.2
  mime: ^0.9.6+3
  progress_dialog: ^1.2.0
  services : ^0.0.1
  intl : ^0.16.1
  # audioplayer: ^0.5.2
  audioplayers : ^0.15.1
  flutter_tts: ^2.1.0


dev_dependencies:
  flutter_test:
    
    sdk: flutter



flutter:
  assets:
    - assets/speech.mp3
  uses-material-design: true

